#!/usr/bin/env python
# -*- coding: utf-8 -*-

from socket import gethostname
from time import time
from argparse import ArgumentParser


def main(prefix):
    timestamp = int(time())
    tpl = '{prefix}.cpu.total.{key} {value} {timestamp}'
    metrics_keys = ['user', 'nice', 'system', 'idle', 'iowait', 'irq', 'softirq', 'steal', 'guest', 'guest_nice']

    with open('/proc/stat') as f:
        while True:
            try:
                line = f.next().split()
                if line[0] == 'cpu':
                    metrics = dict(zip(metrics_keys, line[1:]))
                    for key, value in metrics.iteritems():
                        print(tpl.format(prefix=prefix,
                                         key=key,
                                         value=value,
                                         timestamp=timestamp))
                    break
            except StopIteration:
                break


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('--scheme', default=gethostname(), help='Metric naming scheme')
    args = parser.parse_args()
    main(prefix=args.scheme)
